### ISSUE TITLE
Fix Circle CI not building even though there is a circle.yml file in the project

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/web-jam-front#13]
![image](https://cloud.githubusercontent.com/assets/13340120/23770274/70477866-04e0-11e7-9f92-0031fa92c6c3.png)

**Comment by JoshuaVSherman** [comment]
@LinuxBozo 
Adam, if you get a chance, would you please look into why I can no longer get the tests to run for this repo please?
I moved it into a different org now it doesn't run the tests. It says there isn't any circle.yml file, but there is on, so i'm confused.
thanks, Josh

**Comment by LinuxBozo** [comment]
Should be good now. Just needed to have the key updated. In Circle, you can do this by going to the project list, and clicking on Stop Building and then re-add it to Circle.
