### ISSUE TITLE
Fix an issue with Safari no longer loading at all ...

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/web-jam-front#77]
This could be the reason maybe?
https://github.com/aurelia/skeleton-navigation/issues/748#issuecomment-290449082

@WebJamApps/handlersandkickers 
call out again to the whole team, I am still stuck on this issue, strange but it seems to work fine locally, but it fails to load from Safari within the prod (backend/frontend/dist), and suggestions?

I have a browserstack iphone emulator if anyone wants access, let me know and i'll ping you the credentials

**Comment by JoshuaVSherman** [comment]
@freethlua 
Hey Freeth, could you please take a look at this issue?
it is a real blocking problem, as we do need to support Safari.
Thanks, Josh

**Comment by LinuxBozo** [comment]
@JoshuaVSherman current prod web-jam is loading in both Mac and iPhone Safari for me. Just FYI.

**Comment by JoshuaVSherman** [comment]
From the back, npm run cleaning all
Npm start

**Comment by JoshuaVSherman** [comment]
Npm run cleaninstall

**Comment by JoshuaVSherman** [comment]
@WebJamApps/handlersandkickers 
it appears that this is an issue with Browserstack Safari emulator not able to load
localhost:7000
it works fine when I load web-jam.com
sorry for the confusion
