### ISSUE TITLE
navigation directly within url to /band fails

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/web-jam-front#78]
![image](https://cloud.githubusercontent.com/assets/13340120/24518392/d7dc229a-154f-11e7-9818-56d51e7bc189.png)

also affects ability to use the back arrow in the browser too

@Coletrane please fix this asap, thank you

**Comment by JoshuaVSherman** [comment]
@Coletrane @chemmom2 
This also affects issue #8

**Comment by JoshuaVSherman** [comment]
@WebJamApps/handlersandkickers 

i'm making an all call to the entire team on this issue, if anyone knows how to fix it.
I would like to start working on an actual client's website, but this seems to be an important issue to get resolved before I have him beta test his site.

**Comment by LinuxBozo** [comment]
@JoshuaVSherman The referenced PR WebJamApps/web-jam-back#15 should fix this.
